### PR TITLE
Add new context menu and render HTML content

### PR DESCRIPTION
**Pull request by avdevs**
Hello, 
I have add some context menu to make cell text bold and make cell highlighted. 
Add new div for make table responsive as : http://getbootstrap.com/css/#tables-responsive
Also made change for render HTML in cell to add html content like image and link.

### CODE REVIEW

**Comment by Mesuva** [comment]
Wow, this looks great.

My only concern is that red, green and orange are quite specific colours, it's not really a generic solution to highlighting.  I think I'd prefer more generic options like 'bold', 'italic', 'highlight'.

I think for a highlight just something like a yellow would be find, because it could then be overridden easily.

**Comment by avdevs** [comment]
Hello Mesuva, 
I have updated context menu. 
Do you have any idea how can i show tick mark/right sign with custom menu if cell is bold/italic/highlighted ?

**Comment by Remo** [comment]
@Mesuva this is something I'd like to use. Any chance we can get this merged?

**Comment by Mesuva** [comment]
Sorry for my lack of reply to this.

The updates look good @avdevs. I haven't tested it as such, but I'm happy to merge it!

**Comment by Remo** [comment]
@avdevs I have a bit of a problem, when I add a new block I see a bunch of null values. Any idea what's wrong there? Testing with concrete5.7.5.4

image

**Comment by avdevs** [comment]
@Remo I will check it let you know with solution.

**Pull request merged**
